fx_version 'cerulean' 

game 'gta5'

author 'MrLoeScripts'

description 'Engine Sound Resource'

files {
    'audioconfig/**/*.dat151.rel',      -- Includes all .dat151.rel files in 'audioconfig' and its subfolders
    'audioconfig/**/*.dat54.rel',       -- Includes all .dat54.rel files in 'audioconfig' and its subfolders
    'audioconfig/**/*.nametable',       -- Includes all .nametable files in 'audioconfig' and its subfolders
    'sfx/**/*.awc'                      -- Includes all .awc files in 'sfx' and its subfolders
}

data_file 'AUDIO_GAMEDATA' 'audioconfig/str02213bt_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str02213bt_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str02213bt'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str021m3e30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str021m3e30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str021m3e30'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str020rb26_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str020rb26_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str020rb26'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str1520gdi_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str1520gdi_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str1520gdi'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str12392m_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str12392m_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str12392m'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str11m156_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str11m156_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str11m156'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str10b302_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str10b302_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str10b302'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str9fa20_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str9fa20_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str9fa20'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str7ar4c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str7ar4c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str7ar4c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str6sr20_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str6sr20_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str6sr20'
data_file 'AUDIO_GAMEDATA' 'audioconfig/str4ls7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str4ls7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str4ls7'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq97toy1jzgte_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq97toy1jzgte_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq97toy1jzgte'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq93bmws55_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq93bmws55_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq93bmws55'
data_file 'AUDIO_GAMEDATA' 'audioconfig/strej20_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/strej20_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_strej20'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq91hellcatv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq91hellcatv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq91hellcatv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/strvq35_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/strvq35_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_strvq35'
data_file 'AUDIO_GAMEDATA' 'audioconfig/strf20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/strf20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_strf20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/prg25tfsi_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/prg25tfsi_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_prg25tfsi'
data_file 'AUDIO_GAMEDATA' 'audioconfig/prgc30a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/prgc30a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_prgc30a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq22honb18c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq22honb18c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq22honb18c'
